### ISSUE TITLE
Alert_every

### ISSUE THREAD

**Issue by kdu2** [IamTheFij/minitor#5]
is there a good way to set this to only alert when it's back up after the 1st failure? We just want 1 notification. even with -1 it still sends a bunch before it backs off all the way.

**Comment by IamTheFij** [comment]
Sorry for not responding sooner. For some reason email notifications did not default to enabled for this project!

There is no setting to set it to never alert again after the first, but you could set this to an arbitrarily large value. For example, using a value of `86400` should only alert once a day.

**Comment by IamTheFij** [comment]
This is a good idea and simple enough to implement. I'm releasing v1.0.0 with this feature now.
