### ISSUE TITLE
Log level configuration

### ISSUE THREAD

**Issue by fmartinou** [IamTheFij/minitor#6]
Hello,

Is it possible to customize the log level? (I only want to print ERROR messages).
Changing the level with an environment variable would be perfect.
E.g: `logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))`

--
Regards

**Comment by IamTheFij** [comment]
This was on my to do list for a while. Thanks for the reminder. Working on a patch to instead use command line args.

I'm releasing 1.0 now and it will default to `ERROR`. Adding `-v` does `WARNING`, `-vv` for `INFO`, and `-vvv` for `DEBUG`.
