### ISSUE TITLE
Build docker image on RPi3 fails

### ISSUE THREAD

**Issue by Bouni** [IamTheFij/minitor#7]
Hi,

first of all, thanks for this nice little monitoring tool! 

I try to build a docker image on a RPi3 because I would like to add some minor changes.
So I tried `make docker-cross-build-arm` which resulted in 

```
Step 6/18 : RUN apk --no-cache add bash=~5.0 curl=~7.67 jq=~1.6
 ---> Running in b7eee928e7d6
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/armhf/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/armhf/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  curl-7.69.1-r0:
    breaks: world[curl~7.67]
The command '/bin/sh -c apk --no-cache add bash=~5.0 curl=~7.67 jq=~1.6' returned a non-zero code: 1
make: *** [Makefile:131: docker-cross-build-arm] Error 1
```
Any ideas how to get this working?

**Comment by Bouni** [comment]
I worked around this by replacing the `curl=~7.67` with `curl>=7.67` for the moment. Can this lead to a problem or is this just fine?

**Comment by IamTheFij** [comment]
Newer version of curl is now used.
